{% set name = "sanic" %}
{% set version = "0.7.0" %}
{% set sha256 = "22b1a6f1dc55db8a136335cb0961afa95040ca78aa8c78425a40d91e8618e60e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py<35]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - httptools >=0.0.9
    - ujson >=1.35
    - uvloop >=0.5.3  # [not win]
    - websockets >=4.0
    - aiofiles >=0.3.0

test:
  imports:
    - sanic
    - sanic.app
    - sanic.blueprints
    - sanic.config
    - sanic.constants
    - sanic.cookies
    - sanic.exceptions
    - sanic.handlers
    - sanic.log
    - sanic.request
    - sanic.response
    - sanic.router
    - sanic.server
    - sanic.static
    - sanic.testing
    - sanic.views
    - sanic.websocket
    - sanic.worker  # [not win]

about:
  home: https://github.com/channelcat/sanic
  summary: "Async Python 3.5+ web server that's written to go fast"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - nicoddemus
