{% set name = "sanic" %}
{% set version = "0.8.2" %}
{% set sha256 = "22787b423da53ff707fa20f0bb35b93e75849f0a8dbd615e8a320049e9c7c773" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py<35]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - httptools >=0.0.9
    - ujson >=1.35  # [not win]
    - uvloop >=0.5.3  # [not win]
    - websockets >=5.0,<6.0
    - aiofiles >=0.3.0
    - multidict >=4.0,<5.0

test:
  imports:
    - sanic
    - sanic.app
    - sanic.blueprints
    - sanic.config
    - sanic.constants
    - sanic.cookies
    - sanic.exceptions
    - sanic.handlers
    - sanic.log
    - sanic.request
    - sanic.response
    - sanic.router
    - sanic.server
    - sanic.static
    - sanic.testing
    - sanic.views
    - sanic.websocket

about:
  home: https://github.com/channelcat/sanic
  summary: "Async Python 3.5+ web server that's written to go fast"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - nicoddemus
