travis:
  secure:
    BINSTAR_TOKEN: PqxkgVV1a/hr4q4Fnz2SVajDXIJhQog34DGsfBz8/BT8xR+2UrIVGyBlYct2y/p0K5I8VGCVdZTscq13nkwzTM4ct88wotTH6ZUf9gae7RXgaMgB31fLveywGu8dTSOpYkSVq0zM0EUNLD8qN/uOJdv89zDPDAhLrl2VOE2VIBTtq9PyvDHEeYRabNwbtxygmdW3QrUZrB4b/quvD/Y7t04JG/vPIP0Q5iXsCGyJtee5LnJRSFJl36LB/TTOtdQHa4oZ1a9gAoIYJtzHv+eFdeGoGwqMu9SRQdye37VJiEJ6b4/OxhCVFy3NEFdAHxQt9nwrBGPQeCvzDxLlpOUl+Gcvsj7O+LBYyKJmnx7dQ3kZiLY5kSPvgND+GjiWiViNKXmCTbogG/7oQ2q3xZsDOQHOIbHbCmAPbu+ZoKfY6e4K9qnqmDxZZeH80DAaCpCF20uoAbZ556e5Pkrtv/RBbdf42W9uvCNr153FikimYNuu4VECw3U3Em/J9T/rL2lbSJGyuVdhdLwKV8ziCtvfis8uKdC03wsJjPjyIj1kOsdMieJpxLGG2Fh5etVj7ED2a/T7c5GTm0/ygSkVRQmYBTtMKma4c7gZ5UIpDzPB1u20vBmvpx7g+BOKqRURsjep+ol/tlOiRuqqyr3tK6LMVK0j/y3+bIc9BN8ccCw0cMU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
