travis:
  secure:
    BINSTAR_TOKEN: deSNUqL6cuMDRa8QwavQTN+OTp8zlBt6ftR1H6PQab7HCGFXpf56oK+OHnx8Yay6xzrdcH9j7KZ2vznBozU0hE8YVRNm10k2CULGia9fn7/pVNQHWlCul5LuKBDKHJlYr0VHU9/zUP90ggzNkiFK5k33VrJxU8bzkjm6I7LWbuHlN65UW0bo1h3khW4BxlLIHyOf7F3OxyRXy7KORh3WGc6k1WvsPUvJmPl9kE7kqiByRVLMHbCIr9HdCVvGCGH2u+ZtoN3kSBIeHfty+iJdiHML35JLOUNh93tLVkTxm4pkVxp0GjWWLPShZIVvs6vgR0dKKMAHsX8eM3mOwlIJgbvIeCwPNaWzvWy7wZ/cZJbEn0M7pDlMkkX18vP9hAKEXNdStk8fTggBjoUmgqGMJgiQ3j6ML85s/Y4UewR8ioEdIofhU80Z21jnJ+aCwqa/azOKSv6yGGuCQQJpjYHQItxGH4GgZPqeTBdxh5KzCoO8dK9jItB4FmTgqGayQvMdRjdyS43Z1cx6YVFJGkz3bBAOlDxRKHRnZSvPFxu43BSFQ5UhkM3rmv6wHyJpSFDN21PKYr9EAv2sq2VPdhckWrsukvzO8cD6US2+8Tta0Tpl8GQQQpd4/Xigs+WGoghZJZLreJgZuuDu20lhXiI2boOGCGQkIoY0S6g0zDjucpE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
